### ISSUE TITLE
https cert for the AWS server is invalid

### ISSUE THREAD

**Issue by thearkadia** [Voluntarynet/Bitpost#24]
<img width="679" alt="screen shot 2017-12-16 at 2 26 37 pm" src="https://user-images.githubusercontent.com/6326785/34073692-2aaaea84-e26d-11e7-98be-f68950bc4354.png">

**Comment by ebonsi** [comment]
Hello, the download address has been blocked by all browsers pointing to a misconfiguration on the AWS server https address. (https://voluntary.net.s3.amazonaws.com/Bitpost.0.9.8.3.zip) Could you please, fix that so people can download the app. Thanks!
![bitpost-error-message-02](https://user-images.githubusercontent.com/889908/41332933-92377d6c-6e94-11e8-95b3-fd3a533ea724.png)

**Comment by stevedekorte** [comment]
Thanks for the bug report. I've moved the download to the voluntary.net site. Should work now.
